BACKUP DATABASE [XXXXXAIRWATCHDBXXXXX] TO  DISK = 'C:\Backup\XXXXXAIRWATCHDBXXXXX_FULL.bak' WITH  RETAINDAYS = 7, NOFORMAT, INIT,  NAME = 'XXXXXAIRWATCHDBXXXXX-Full DB Backup', SKIP, NOREWIND, NOUNLOAD,  STATS = 10
GO
