USE [master]
ALTER DATABASE [XXXXXAIRWATCHDBXXXXX] SET SINGLE_USER WITH ROLLBACK IMMEDIATE
RESTORE DATABASE [XXXXXAIRWATCHDBXXXXX] FROM  DISK = N'S:\Backup\XXXXXAIRWATCHDBXXXXX_FULL.bak' WITH  FILE = 1,  MOVE N'XXXXXAIRWATCHDBXXXXX' TO N'S:\MSSQL12.XXXXXCATXXXXX\MSSQL\DATA\XXXXXAIRWATCHDBXXXXX.mdf',  MOVE N'XXXXXAIRWATCHDBXXXXX_log' TO N'R:\MSSQL12.XXXXXCATXXXXX\MSSQL\DATA\XXXXXAIRWATCHDBXXXXX_log.ldf',  NOUNLOAD,  REPLACE,  STATS = 5
ALTER DATABASE [XXXXXAIRWATCHDBXXXXX] SET MULTI_USER

GO

USE [XXXXXAIRWATCHDBXXXXX]
DECLARE @sql NVARCHAR(MAX)
IF NOT EXISTS (SELECT * FROM sys.database_principals WHERE name='XXXXXDBUSERXXXXX')
BEGIN
EXEC sp_adduser
		@loginame   =  'XXXXXDBUSERXXXXX' 
    ,  @name_in_db =  'XXXXXDBUSERXXXXX' 
     ,  @grpname    =  'db_owner' 
END
ELSE
BEGIN
EXEC sp_addrolemember 'db_owner', 'XXXXXDBUSERXXXXX'
END